### ISSUE TITLE
Finish paper

### ISSUE THREAD

**Issue by dsondak** [lindseysbrown/Auto-eD#20]
Things to do / address to finish up the paper:

* Would be cool to show a demo in the content section. It looks like some of the other JOSE papers have done this. We could show the graph structure.
* Fix notes in text:
    - CHECK FINAL NAMES
* I added this line: "To make sure this final option is still     
accessible to students with limiting coding experience, the code documentation provides detailed steps on how to launch      
locally". Is this in the docs?

**Comment by lindseysbrown** [comment]
1.  Were you thinking of just adding a picture like the one on the github cover page or something else?
2.  Will address this week.
3.  There's a jupyter notebook called DeveloperDocumentation that has those instructions.  However, I just noticed that it is still missing the instructions that we said we'd get back to later on how to contribute to the code.

**Comment by dsondak** [comment]
> 1. Were you thinking of just adding a picture like the one on the github cover page or something else?
> 2. Will address this week.
> 3. There's a jupyter notebook called DeveloperDocumentation that has those instructions.  However, I just noticed that it is still missing the instructions that we said we'd get back to later on how to contribute to the code.

Yes, I was thinking something like that for point 1.

Can we update the DeveloperDocumentation?

**Comment by lindseysbrown** [comment]
Yes, we can update the DeveloperDocumentation, but I don't think we decided what to update it to say  for that section.  If they want to contribute to the code, they should make a pull request?  Email someone?  Just fork the repo and use it, crediting the original?

**Comment by dsondak** [comment]
This is partly up to you, Lindsey, because you are the main developer. Personally, I'd like to see the package stay as one piece with different groups contributing. This means that we need to have fairly clear instructions on how to do this. If they want to contribute, they should definitely make a new branch. They should create an issue. They should open a PR to main. I don't think a Kanban board is necessary, since this will be such a distributed project once it's out in the wild. Milestones also don't make sense externally. You will still need to approve the PRs. I think you can also give me permission to do so as well.

**Comment by lindseysbrown** [comment]
1.  I have added the image to the paper.  
2.  I also don't think the lines on the command line use are correct as written - I'd propose just cutting them.
3.  I don't think the references are compiling within the paper? 

Future work of the DeveloperDocumentation.ipynb is also edited for the process you proposed above.
