### ISSUE TITLE
paper.md comments

### ISSUE THREAD

**Issue by rachelmoonstar** [lindseysbrown/Auto-eD#25]
## General
1. Not sure what is going on with line breaks of all the sentences.

## Accompanying Automatic Differentiation Unit
1. "... Manual exercises are complemented with the `Auto-eD` web application. .... Each module is accompanied by a series
of exercises."  
This sounds a bit redundant. Also, the first sentence applies to module 1~3, not just to module 2. Maybe remove the first sentence and change the last sentence to: "Each module is accompanied by a series of exercises, and modules are complemented with the `Auto-eD` web application." 
2. Mentions "module 4", but our readthedocs do not have "module 4" but rather just calls it "Beyond the Basics..." We should make this coherent.

**Comment by lindseysbrown** [comment]
Updated Read the Docs to have module 4.

On my end, line breaks seem ok - I think it's only viewing the file in vim that there are breaks.  And looks good in the journal preview.
