### ISSUE TITLE
Readthedocs comments

### ISSUE THREAD

**Issue by rachelmoonstar** [lindseysbrown/Auto-eD#26]
## General
Footer: should it be updated like the Auto-eD web app -- year, name, IACS? Or is this separate thing?
There is only one way to reach Auto-eD web app, through the link in a particular section in Module 1. Should we put the link to other modules too, for easier access?

### Auto-eD Web Application
"This option is good for people who want to explore automatic differentiation." --> is this sentence needed?

### a.Evaluating the Function
"We will choose the point a=2. Throughout this documentation, we will refer to a specific point with the name a. It should be assumed that a has a specific value (e.g. 2)."  --> Not sure what "a" is and what exactly eg2 refers to.

## The Original Demo
"The visualization tool which we installed in the first module also computes the computational table." 
--> Does this refer to web app, or code? The word "installed" makes the sentence a bit confusing.

### Demo: A Comparison of Forward and Reverse Mode 
"dynamic visualization tool" --> meaning the reverse mode graph steps in the web app? 
### Exercise
"dynamic visualization tool"
"Let's return to the function that we used the computational tool to dynamically visualize the steps of the reverse mode." --> For clarity, change "computational tool" to "Auto-eD web app"?

**Comment by lindseysbrown** [comment]
Updated per comments.  I think visualization tool might be clearest since that's the language we use in the headings so have left that language.
