### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by rasbt** [lindseysbrown/Auto-eD#27]
Hey there,
I am currently reviewing this submission for JOSE and was going through the checklist. One item is 

> Version: Does the release version given match the GitHub release (v1.0.0)?

Could you add the version number to the code (maybe I am not seeing it) and make a GitHub release with that version?

**Comment by lindseysbrown** [comment]
I have now added:
1. Version badge to the readme.
2. Tagged the git repo with the version number, so that git describe command works.
3. Added version.py file

**Comment by rasbt** [comment]
Awesome, thanks! I can see the version in the Readme now, and there is also the version.py file.

Sorry, but I still can't see the tag though. When I go to https://github.com/lindseysbrown/Auto-eD/tags it looks empty.

**Comment by lindseysbrown** [comment]
I didn't realize the tags didn't push automatically.  (I could see it locally with git describe).  Pushed now.

**Comment by rasbt** [comment]
Perfect, can see it now!
