### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by rasbt** [lindseysbrown/Auto-eD#28]
Moving to the next point in the JOSE reviewer instructions, there is the item

> Installation: Does installation proceed as outlined in the documentation? (and documentation is sufficient?)

Where would I find the installation instructions? I think it's a bit tricky because it's a webapp. I am not 100% sure how the instructions should look like and maybe @labarba can help clarify whether this should be

a. Instructions for how to deploy the code here as a webapp on Heroku?
b. How to install the underlying Python package?

**Comment by lindseysbrown** [comment]
For the package, we point users to DeveloperDocumentation.ipynb (both in the README and the paper).  That includes a set of installation instructions.  (Was this unclear or the question is really about how to evaluate installation instructions of a web app?)

**Comment by rasbt** [comment]
Thanks, now that you mention it, I see there is a link in the paper. However, I don't think the repo README.md (https://github.com/lindseysbrown/Auto-eD) contains a link or reference. Could you add it? 

PS: It is currently a bit unclear if this (the instruction for the package installation) is enough, or if installation instructions also should contain something on setting up the webserver @labarba. I guess the challenge here is that there are really two types of things: the python package and the GUI &  webserver, and which one do the reviewer instructions / checklists refer to?

**Comment by lindseysbrown** [comment]
README.md now explicitly refers readers to DeveloperDocumentation.ipynb for installation instructions for the package.

The web application is accessible via the URL so there's not really any installation to be done.

**Comment by rasbt** [comment]
Thanks for adding it. Yeah, since the software can also be run locally via `python ADapp.py`, we probably don't need to review the webapp part.
