### ISSUE TITLE
Flask/json issue after installation

### ISSUE THREAD

**Issue by rasbt** [lindseysbrown/Auto-eD#30]
I followed the instructions in the `DeveloperDocumentation.ipynb` to install the requirements & app in a fresh environment. Upon running 

    python ADapp.py

I get the following error:

```
(auto-eD) sebastian@Sebastian-Air ~/Desktop/Auto-eD % python ADapp.py
Traceback (most recent call last):
  File "/Users/sebastian/Desktop/Auto-eD/ADapp.py", line 1, in <module>
    from flask import Flask, render_template, redirect, url_for, request, Response, session, jsonify
  File "/Users/sebastian/miniforge3/envs/auto-eD/lib/python3.9/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/Users/sebastian/miniforge3/envs/auto-eD/lib/python3.9/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/Users/sebastian/miniforge3/envs/auto-eD/lib/python3.9/site-packages/itsdangerous/__init__.py)
```

I think this is related to https://exerror.com/importerror-cannot-import-name-json-from-itsdangerous/ and there are 4 different suggestions for how to fix this. Could you choose one and update the requirements file? Ideally Flask 2.x, but in order to minimize the work required, the other ones sound fine to me too. It's just that I think others installing this would bump into the same issue, and it should be addressed in some way.

**Comment by rachelmoonstar** [comment]
Hi, thank you for your feedback and also sharing with us suggestions on how to fix the issue. I just tested as well on a fresh new virtual environment and confirmed that the web application is running locally after updating the requirements file to Flask=2.x. Please let us know if you encounter any other installation issues along the way.

**Comment by rasbt** [comment]
Thanks, this works now! 

One little follow-up issue, and maybe that should be mentioned in the installation docs. I think port 5000 is usually used for system services (at least for macOS), so that wouldn't work if you run it on a MacBook. I am not an expert in this, but in general, isn't the common one 8000? At least in my case I had to change it from 5000 to 8000 to make it work. Maybe that should be a note in the installation between the steps 

    pip install -r requirements.txt

and 

    python ADapp.py

or below.

**Comment by rachelmoonstar** [comment]
Port 5000 is commonly used for local development purposes, but you are right that the recent MacOS Monterey version now uses port 5000 for AirPlay receiver (https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c). I changed the default port to 8000 to minimize confusion for the users. Thank you for your suggestion!

**Comment by rasbt** [comment]
Thanks for the explanation and update!
