### ISSUE TITLE
Missing community guidelines

### ISSUE THREAD

**Issue by rasbt** [lindseysbrown/Auto-eD#34]
Hey, another thing for the JOSE review is the following point:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Maybe you could just add it as a separate sections in the Readme. Maybe two sections

## Getting Help

...

## Contributing

...

should suffice?

**Comment by lindseysbrown** [comment]
Hi @rasbt, we had noted in the DeveloperDocumentation under Future Work how to contribute to the software, but I have now added the notes you requested in the README as well.

**Comment by rasbt** [comment]
I think this should be sufficient. Thanks!
