### ISSUE TITLE
Add missing references

### ISSUE THREAD

**Issue by rasbt** [lindseysbrown/Auto-eD#35]
Hey,

almost there. Just a few final things to check off for the review! There is the item

> References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

I just see that the paper's Reference section is blank. Could you fill it in with the required details?

**Comment by lindseysbrown** [comment]
Hi @rasbt , I think that's how the journal's paper building system is set up.  (If you check the repos for recently published papers, the References section shows blank for all of them in github.)  References are listed in paper.bib.  I just rechecked doi's - not finding one for Greiwank 1989 but I have been able to track them down for the other citations.

**Comment by rasbt** [comment]
Sounds good! Could you add the correct citation for the Andreas Griewank entry though please:

```
@article{griewank1989automatic,
  title={On automatic differentiation},
  author={Griewank, Andreas},
  journal={Mathematical Programming: recent developments and applications},
  volume={6},
  number={6},
  pages={83--107},
  year={1989},
  publisher={Amsterdam}
}
```
this doesn't look right to me. I think it's a book, and the publisher is Kluwer. So, this article would be a book chapter part of the book.

**Comment by lindseysbrown** [comment]
Sorry.  It's been updated now.

**Comment by rasbt** [comment]
Looks good to me!
