### ISSUE TITLE
Heroku page not working

### ISSUE THREAD

**Issue by fedebenelli** [lindseysbrown/Auto-eD#36]
Hi! I'm in the process of making a seminar about automatic differentiation and this project seems perfect to show some examples! 

Unfortunately, the Heroku page isn't working :(

**Comment by lindseysbrown** [comment]
Somehow, I missed the notification regarding this issue - so sorry!  You caught us in the middle of migrating to a new platform for the app since heroku moved away from free support for open source.  Should you need it again, the app is now back up on Render https://autoed.onrender.com/
